#! /bin/sh

# pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        4
bspc config window_gap          4
bspc config top_padding         25
bspc config border_radius       0

bspc config split_ratio          0.5

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a barve desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color "#80C2C0"
bspc config active_border_color  "#80C2C0"
bspc config normal_border_color  "#0C363F"
#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Bar
~/.config/polybar/launch.sh &

# sxhkd (Hot Key Deamon)
killall -q sxhkd; sxhkd &

# Notifications
# /usr/bin/dunst &
killall -q dunst; dunst -conf ~/.config/dunst/dunstrc &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
# nitrogen --restore &
DISPLAY=:0 feh --bg-scale --randomize ~/Pictures/Wallpapers/*

# Dex
# dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &

# Picom
# picom -b &
killall -q picom; picom --experimental-backends --config ~/.config/picom/picom.conf &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh &


