#! /bin/sh

sleep 10 && $HOME/.config/bspwm/scripts/bspfloat floating 5 &> $HOME/.log.bspfloat.txt &

# polybar
polybar &

# sxhkd keys
pgrep -x sxhkd > /dev/null || sxhkd &

# eww
eww daemon &

# scree board
$HOME/.config/conky/Auva/start.sh &

# polkit authentication agent
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# power manager
xfce4-power-manager &

bash $HOME/.config/bspwm/scripts/fix-plank

# cursor
xsetroot -cursor_name left_ptr &

# compositor
picom &

# wallpapers
DISPLAY=:0 feh --bg-scale --randomize ~/.wallpapers/walls/*

ukui-window-switch &
parcellite &
plank &

bspc monitor -d 1 2 3 4 5

bspc config border_width        3
bspc config window_gap          8
bspc config border_radius	    15

bspc config normal_border_color  c0caf5
bspc config active_border_color  ${colors.background-alt}
bspc config focused_border_color ${colors.background}

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Peek state=floating
#bspc rule -a kitty state=floating
bspc config external_rules_command "$HOME/.config/bspwm/scripts/external-rules"
bspc rule -a conky-manager2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Plank manage=off border=off locked=on focus=off follow=off layer=above
bspc rule -a Rofi state=floating
bspc rule -a GLava state=floating layer=below sticky=true locked=true border=off focus=off center=true follow=off rectangle=1920x1080+0+0
